[package]
name = "nrd"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.34"
dirs = "6.0.0"
promptuity = "0.0.5"
serde = { version = "1.0", features = ["derive"] }
serde_yml = "0.0.12"
structopt = "0.3.26"
