[package]
name = "nrd"
version = "0.1.0"
edition = "2024"

[dependencies]
config = { version = "0.15.11", features= ["yaml"]}
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
serde = { version = "1.0", features = ["derive"] }
serde_yml = "0.0.12"
